#+title: Introduction


Understanding the demographic history and population structure of /P. falciparum/ is crucial to make valid inferences about disease transmission patterns and different selection pressures, such as drug resistance, contributing to the evolution of this malaria parasite.

* Importance of accounting for demography
Not only is demography important when accounting for signals of selection, but also relates directly to the epidemiology, as high levels of gene flow and recombination are brought about by high levels of infection and transmission.
- account for demography, when infering life-history traits from coalescent models. Multiple merger models are better?
* Importance of selection


* How can demography skew inferences about selection? What happens if we do not account for population structure?
* How does the transmission dynamics and recombination influences genetic variation? What does this mean for control measures and vacciens? What do high levels of gene flow mean for effective control strategies?
* How does the U-shaped sfs influence typical selection inference? Use of multiple merger models?
